In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])

In [ ]:
# 1st question
print(arr)
arr[2]=100
print("updated array",arr)

[1 2 3 4 5]
updated array [  1   2 100   4   5]


In [ ]:
# 2nd question
a=np.eye(4)
print(a)
b=np.eye(4,k=2)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 3rd question
a=np.array([5,10,25,20,25,30])
print(a[::2]) # index based even
print(a[1::2]) # position based even

[ 5 25 25]
[10 20 30]


In [ ]:
# 4th question
# create random 3X3 array
a=np.random.randint(10,51,size=(3,3))
print(a)
# extract last colum
print(a[:,2])
# or
print(a[:,-1])

[[19 10 22]
 [44 30 46]
 [14 20 24]]
[22 46 24]
[22 46 24]


In [ ]:
# 5th question
a=np.array([[12,24],[36,48],[60,72]])
# to print totla number of elements
print("total number of elements",a.size)
# shape
print("shape ",a.shape)
# dimensions
print("dimensions",a.ndim)

total number of elements 6
shape  (3, 2)
dimensions 2


In [ ]:
# 6th question
# create 1D array of 12 elements  using np,arange()
a=np.arange(12) # or np.arange(0,12)
print(a)
# reshape to 3x4
print(a.reshape(3,4))
# (or) in one line
b=np.arange(12).reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 7th question
d=np.array([[5,15],[25,35],[45,55]])
print(d)
# transpose of this matrix using .T
a=d.T
print(a)
# modify any element in transepose matrix
a[0,1]=500
print(a)
print(d) # so transpose matrix  shares memory with original matrix



[[ 5 15]
 [25 35]
 [45 55]]
[[ 5 25 45]
 [15 35 55]]
[[  5 500  45]
 [ 15  35  55]]
[[  5  15]
 [500  35]
 [ 45  55]]


In [ ]:
# 8th question
# create an array of 6 elements
z=np.array([1,2,3,4,5,6])
print(z)
# resize it into 2x3 matrix
z.resize(2,3)
print(z)
# resize to a large shape 3x3 matrix
z.resize(3,3)
print(z)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [ ]:
# 9th question
d=np.array([15,22,8,19,33,4,27])
# greater then 15 using boolean indexing
print(d[d>15])

[22 19 33 27]


In [ ]:
# 10th question
# 3x3 array with all elements set to 7 using np.full()
a=np.full((3,3),7)
print(a)
# transpose
b=a.T
print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [3]:
d=np.array([15,22,8,19,33,4,27])
print(d)

[15 22  8 19 33  4 27]


In [4]:
d.ndim


1

In [5]:
d.shape

(7,)

In [7]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a=np.ones([4,2])
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
a=np.full(10,2)

In [17]:
a=np.full([10,2],7)
print(a)

[[7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]]


In [19]:
a=np.empty([2,3])
print(a)

[[6.31648620e-316 0.00000000e+000 2.16443571e-312]
 [2.27053550e-312 1.16318369e-028 9.53656312e+151]]


In [21]:
a=np.random.rand(20)
print(a)

[0.28066588 0.4675415  0.89108195 0.8647209  0.20674032 0.87092587
 0.21143222 0.01455855 0.28876227 0.60691127 0.36274119 0.39758785
 0.83425107 0.59051872 0.83944269 0.23462061 0.91751118 0.96794375
 0.41979267 0.29197294]


In [22]:
a=np.random.rand(20,3)
print(a)

[[0.51079513 0.78664625 0.19583191]
 [0.55334383 0.11803781 0.14681914]
 [0.27667721 0.58162629 0.05051452]
 [0.42141782 0.06694573 0.76339372]
 [0.6236778  0.79473671 0.92557536]
 [0.17103045 0.26502302 0.7789874 ]
 [0.65404847 0.1705367  0.76286439]
 [0.10417318 0.06739536 0.9501991 ]
 [0.81439958 0.54179575 0.42469713]
 [0.81421124 0.50471036 0.82063714]
 [0.69192949 0.29869211 0.65627564]
 [0.86906636 0.47340696 0.67622452]
 [0.59146403 0.2092065  0.20129956]
 [0.12948197 0.46976487 0.89288713]
 [0.6941111  0.01350229 0.27810793]
 [0.89724618 0.76848842 0.35030074]
 [0.52732557 0.34410945 0.85048879]
 [0.42780822 0.90132194 0.93625   ]
 [0.76182858 0.49432157 0.75760335]
 [0.61482965 0.07304796 0.36707301]]


In [24]:
a=np.random.randn(2,3)
print(a)

[[ 1.78695676  0.60338111  1.50598759]
 [ 0.91348266 -1.66368415 -0.24571237]]


In [26]:
a=np.random.randint(10,100)
print(a)

43


In [27]:
a=np.random.randint(10,100,size=(2,3))
print(a)

[[24 86 59]
 [49 86 65]]


In [30]:
a=np.array([1,2,3])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [31]:
a.size

3

In [32]:
a.itemsize

8

In [34]:
a=np.array([1,2,3,4])
b=a.reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [36]:
b=a.ravel()
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [37]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])


In [38]:
print(a+b)

[2 4 6 8]


In [39]:
print(a-b)

[0 0 0 0]


In [40]:
print(a*b)

[ 1  4  9 16]


In [41]:
print(a/b)

[1. 1. 1. 1.]


In [42]:
print(a//b)

[1 1 1 1]


In [43]:
print(a**2)

[ 1  4  9 16]


In [45]:
a=[1,2,3,4]
print(a[-1])

4
