In [59]:
import numpy as np
marks=np.array([[14 ,24 , 11 , 23 , 17 ],[ 17, 16 , 15 , 16 ,19 ],[ 20 , 19 , 18 , 20 ,11 ],[ 14 , 13 , 12 , 14 , 19 ]
                ,[ 11 , 10 , 9 , 17 , 20 ],[14 ,24 ,11 , 34 , 56 ],[ 14, 13 , 12 , 35 , 47],[ 17, 16 , 15 , 19 , 76 ],
                 [ 88 , 87 , 84 , 85 , 86 ],[ 14 , 13 , 12 ,  17 , 74 ]])
subjects=["Maths","Python","c","Telugu","English"]
print("\nStudent Marks:")
print("          Maths Python C  Telugu English ")
for i in range(10):
  print("Student",i+1," ",marks[i][0]," ",marks[i][1]," ",marks[i][2]," ",marks[i][3]," ",marks[i][4] )
#students=np.array([" student 1"," student 2"," student 3"," student 4"," student 5"," student 6"," student 7"," student 8"," student 9"," student 10",])



Student Marks:
          Maths Python C  Telugu English 
Student 1   14   24   11   23   17
Student 2   17   16   15   16   19
Student 3   20   19   18   20   11
Student 4   14   13   12   14   19
Student 5   11   10   9   17   20
Student 6   14   24   11   34   56
Student 7   14   13   12   35   47
Student 8   17   16   15   19   76
Student 9   88   87   84   85   86
Student 10   14   13   12   17   74


In [67]:
# total marks of each student
print("total marks of each student:",np.sum(marks,axis=1))

total marks of each student: [ 89  83  88  72  67 139 121 143 430 130]


In [66]:
# average marks of each student
average=np.mean(marks,axis=1)
print("average marks of each student:",average)

average marks of each student: [17.8 16.6 17.6 14.4 13.4 27.8 24.2 28.6 86.  26. ]


In [68]:
# hight marks
print("highest marks:",np.max(marks,axis=1))

highest marks: [24 19 20 19 20 56 47 76 88 74]


In [69]:
# lowest marks
print("highest marks:",np.min(marks))

highest marks: 9


In [70]:
# student with highest average
averages=np.mean(marks,axis=1)
highest_idx=np.argmax(averages)
print("Highest Average Student:",highest_idx+1)


Highest Average Student: 9


In [71]:
# subject wise average
average=np.mean(marks,axis=0)
print("subject wise average :",average)

subject wise average : [22.3 23.5 19.9 28.  42.5]


In [72]:
# student who scored above 80 in all subjects
for i in range(10):
  if np.all(marks[i]>80):
    print(f"Student {i+1}")

Student 9


In [73]:
# subject wise average
average=np.mean(marks,axis=0)
print("subject wise average:",average)

subject wise average: [22.3 23.5 19.9 28.  42.5]


In [74]:
# student who failed in any subject
for i in range(10):
  if np.any(marks[i]<35):
    print(f" Student{i+1}")

 Student1
 Student2
 Student3
 Student4
 Student5
 Student6
 Student7
 Student8
 Student10


In [77]:
# Rank of student based on total marks
totals=list(np.sum(marks,axis=1))
for rank in range(1,11):
  highest_mark=max(totals)
  student_index=totals.index(highest_mark)
  print(f"Rank {rank}:Student {student_index +1} (Total:{highest_mark})")
  totals[student_index]=-1


Rank 1:Student 9 (Total:430)
Rank 2:Student 8 (Total:143)
Rank 3:Student 6 (Total:139)
Rank 4:Student 10 (Total:130)
Rank 5:Student 7 (Total:121)
Rank 6:Student 1 (Total:89)
Rank 7:Student 3 (Total:88)
Rank 8:Student 2 (Total:83)
Rank 9:Student 4 (Total:72)
Rank 10:Student 5 (Total:67)


In [79]:
# class average and standard deviation
class_average=np.mean(marks)
class_std_dev=np.std(marks)
print("class average marks:",class_average)
print("class standard deviation:",class_std_dev)

class average marks: 27.24
class standard deviation: 24.066208675235906


In [82]:
# normalize marks
min_val=np.min(marks)
max_val=np.max(marks)
normalized_marks=(marks-min_val)/(max_val-min_val)
#print(normalized_marks)
print(np.round(normalized_marks,2))


[[0.06 0.19 0.03 0.18 0.1 ]
 [0.1  0.09 0.08 0.09 0.13]
 [0.14 0.13 0.11 0.14 0.03]
 [0.06 0.05 0.04 0.06 0.13]
 [0.03 0.01 0.   0.1  0.14]
 [0.06 0.19 0.03 0.32 0.59]
 [0.06 0.05 0.04 0.33 0.48]
 [0.1  0.09 0.08 0.13 0.85]
 [1.   0.99 0.95 0.96 0.97]
 [0.06 0.05 0.04 0.1  0.82]]


In [83]:
student_averages=np.mean(marks,axis=1)
for i in range(10):
  avg=student_averages[i]
  if avg >=90:
    category="excellent"
  elif(75<=avg<=89):
    category="good"
  elif(50<=avg<75):
    category="average"
  else:
    category="poor"
  print(f"Student {i+1} -> Average: {avg} -> {category}")

Student 1 -> Average: 17.8 -> poor
Student 2 -> Average: 16.6 -> poor
Student 3 -> Average: 17.6 -> poor
Student 4 -> Average: 14.4 -> poor
Student 5 -> Average: 13.4 -> poor
Student 6 -> Average: 27.8 -> poor
Student 7 -> Average: 24.2 -> poor
Student 8 -> Average: 28.6 -> poor
Student 9 -> Average: 86.0 -> good
Student 10 -> Average: 26.0 -> poor
