In [1]:
import torch
# developed by meta
# it is used in
# deep learning
# C.V
# N.L.P
# Generative AI

In [ ]:
a=torch.tensor(3) # 0D
print(a)
print(a.shape)

tensor(3)
torch.Size([])


In [ ]:
a=torch.tensor([8,16,24,32])
print(a)
print(a.shape)
print(a.size())


tensor([ 8, 16, 24, 32])
torch.Size([4])
torch.Size([4])


In [ ]:
a=torch.tensor([[8,16,24,32],[1,4,9,16]])
print(a)
print(a.numel())  # number of elements
print(a.shape)

tensor([[ 8, 16, 24, 32],
        [ 1,  4,  9, 16]])
8
torch.Size([2, 4])


In [ ]:
torch.zeros(3,3)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
print(torch.full((3,3),514))
# print(torch.full((3,3),"a")) # error

tensor([[514, 514, 514],
        [514, 514, 514],
        [514, 514, 514]])


In [ ]:
a=torch.arange(2,35,8)
print(a)
print(a.dtype)
print(type(a))

tensor([ 2, 10, 18, 26, 34])
torch.int64
<class 'torch.Tensor'>


In [ ]:
torch.rand(2,3,8)

tensor([[[0.8931, 0.7922, 0.7988, 0.7595, 0.4751, 0.2115, 0.7087, 0.6115],
         [0.1875, 0.2511, 0.4848, 0.6763, 0.1542, 0.9704, 0.2877, 0.6208],
         [0.4646, 0.1955, 0.9467, 0.9535, 0.6783, 0.9355, 0.9835, 0.9552]],

        [[0.1703, 0.1987, 0.3207, 0.6485, 0.3164, 0.0571, 0.8065, 0.1210],
         [0.4223, 0.0821, 0.5124, 0.8658, 0.0697, 0.3552, 0.1666, 0.8725],
         [0.7832, 0.5652, 0.3717, 0.5368, 0.2593, 0.0155, 0.5605, 0.4829]]])

In [ ]:
torch.randn(2,4) # n=negative and positive

tensor([[-1.2442,  0.3742, -1.0198,  0.5057],
        [ 0.8327,  0.3809, -0.7562, -2.0088]])

In [ ]:
a=torch.tensor([8,16,24,32])
print(a.numel())

4


In [ ]:
print(a.size())

torch.Size([4])


In [ ]:
print(a.shape)

torch.Size([4])


In [ ]:
print(torch.zeros((3,3)))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
print(torch.ones((3,3)))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(torch.full((3,3),100))

tensor([[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]])


In [ ]:
print(torch.arange(2,35,8))

tensor([ 2, 10, 18, 26, 34])


In [ ]:
print(a.dtype)

torch.int64


In [ ]:
print(torch.rand(2,3))

tensor([[0.5764, 0.6566, 0.6571],
        [0.9903, 0.8169, 0.2503]])


In [2]:
a=torch.tensor([[13,36,39],[4,8,12]])
print(a)

tensor([[13, 36, 39],
        [ 4,  8, 12]])


In [3]:
print(a.ndim)

2


In [4]:
print(a.shape)

torch.Size([2, 3])


In [6]:
print(a.numel())

6


In [7]:
print(a.dtype)

torch.int64


In [8]:
print(a.device)

cpu


In [12]:
torch.ones((2,3),dtype=int)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [14]:
torch.ones((2,3),dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [15]:
torch.zeros((2,3),dtype=int)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.rand(2,3)

tensor([[0.4227, 0.5497, 0.9524],
        [0.1426, 0.6046, 0.0559]])

In [17]:
torch.randn(2,3)

tensor([[ 0.2715, -1.5000,  0.7389],
        [ 0.7503, -0.0952, -0.6856]])

In [25]:
a=torch.tensor([[10,12,13],[14,15,16],[17,18,19]])
print(a)

tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


In [26]:
a[[1,2]]

tensor([[14, 15, 16],
        [17, 18, 19]])

In [27]:
a[[1,2],1]

tensor([15, 18])

In [28]:
a[[0,1,2]]

tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [29]:
a[[0,1,2],2]

tensor([13, 16, 19])

In [30]:
a=torch.tensor([[10,12,13],[14,15,16],[17,18,19]])
print(a)

tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


In [31]:
a[0:3,0:1]

tensor([[10],
        [14],
        [17]])

In [32]:
a[:3,0]

tensor([10, 14, 17])

In [34]:
a[:,0]

tensor([10, 14, 17])

In [35]:
a[:,0:1]

tensor([[10],
        [14],
        [17]])

In [36]:
a[2:3,0:3]

tensor([[17, 18, 19]])

In [37]:
a[2:3]

tensor([[17, 18, 19]])

In [38]:
a[-1,:3]

tensor([17, 18, 19])

In [39]:
a[2:3,:3]

tensor([[17, 18, 19]])

In [40]:
a=torch.tensor([[10,12,13],[14,15,16],[17,18,19]])
print(a)

tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


In [41]:
print(sum(a))

tensor([41, 45, 48])


In [42]:
print(torch.sum(a))

tensor(134)


In [43]:
print(a.sum())

tensor(134)


In [46]:
a=torch.tensor([[10,12,13],[14,15,16],[17,18,19]])
b=torch.tensor([[2,8,10],[4,5,6],[10,11,12]])
print(a)
print(b)

tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor([[ 2,  8, 10],
        [ 4,  5,  6],
        [10, 11, 12]])


In [47]:
print(torch.subtract(a,b))

tensor([[ 8,  4,  3],
        [10, 10, 10],
        [ 7,  7,  7]])


In [48]:
print(torch.max(a,b))

tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


In [49]:
print(torch.min(a,b))

tensor([[ 2,  8, 10],
        [ 4,  5,  6],
        [10, 11, 12]])


In [52]:
print(torch.argmax(a))

tensor(8)


In [53]:
a=torch.tensor([70,36,27,50,99])
print(a)

tensor([70, 36, 27, 50, 99])


In [54]:
print(a>50)

tensor([ True, False, False, False,  True])


In [59]:
print([a[a>50]])

[tensor([70, 99])]


In [60]:
print([a[a>34]])

[tensor([70, 36, 50, 99])]


In [64]:
print([a[a<50]])

[tensor([36, 27])]


In [65]:
print(a<50)

tensor([False,  True,  True, False, False])
