In [ ]:
#import tensorflow as tf # attributes ,properties, concatination ,splitting, chunk,slicing and indexing, cpu vs gpu,operating
#x=tf.constant([10,20,30])
#print(x)

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
# its a Data structure
# scalar is zero dimentional tensor
# vector is one dimensional tensor
# matrix is twodimentional vector
# epochs
# neural network
# cpu() & gpu(numerical calculations )

In [ ]:
import torch
x=torch.tensor([10,20,30])
print(x)

tensor([10, 20, 30])


In [ ]:
import torch
a=torch.tensor([6,18,24])
b=torch.tensor([[10,15,18],[20,21,22]])
print(b)
b.shape
print(a)


tensor([[10, 15, 18],
        [20, 21, 22]])
tensor([ 6, 18, 24])


In [ ]:

b.size() # function

torch.Size([2, 3])

In [ ]:
b.shape # attribute

torch.Size([2, 3])

In [ ]:
b.ndim

2

In [ ]:
import torch
a=torch.tensor([6.,18,24])
print(a)

tensor([ 6., 18., 24.])


In [ ]:
a.dtype

torch.float32

In [ ]:
a=torch.full((3,5),7)
print(a)

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])


In [ ]:
a=torch.empty(6)
print(a)

tensor([9.8262e+12, 4.5122e-41, 7.8497e-11, 0.0000e+00, 9.1084e-44, 0.0000e+00])


In [ ]:
a=torch.zeros(1,2)
print(a)

tensor([[0., 0.]])


In [ ]:
a=torch.ones(3,5)
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [ ]:
a=torch.arange(96,108)
print(a)

tensor([ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107])


In [ ]:
a=torch.arange(96,108,6)
print(a)

tensor([ 96, 102])


In [ ]:
a=torch.eye(8)
print(a)

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])


In [ ]:
import torch
a=torch.tensor([514,560,588,720])
print(a)

tensor([514, 560, 588, 720])


In [ ]:
a[2]

tensor(588)

In [ ]:
a[1:4]

tensor([560, 588, 720])

In [ ]:
a[:]

tensor([514, 560, 588, 720])

In [ ]:
a[-2]

tensor(588)

In [ ]:
a.numel() # number of elements

4

In [ ]:
a.device

device(type='cpu')

In [ ]:
import torch
a=torch.tensor([19,36,45,69])
a.reshape(2,2)

tensor([[19, 36],
        [45, 69]])

In [ ]:
a.reshape(4,1)

tensor([[19],
        [36],
        [45],
        [69]])

In [ ]:
a.reshape(1,4)

tensor([[19, 36, 45, 69]])

In [ ]:
import torch
a=torch.tensor([[6,18,24],[1,2,3]])
a.reshape(2,3)

tensor([[ 6, 18, 24],
        [ 1,  2,  3]])

In [ ]:
a.reshape(3,2)

tensor([[ 6, 18],
        [24,  1],
        [ 2,  3]])

In [ ]:
a.reshape(6,1)

tensor([[ 6],
        [18],
        [24],
        [ 1],
        [ 2],
        [ 3]])

In [ ]:
a.reshape(1,6)

tensor([[ 6, 18, 24,  1,  2,  3]])

In [ ]:
import torch
a=torch.tensor([6,20,18,24])
a.reshape(2,-1)

tensor([[ 6, 20],
        [18, 24]])

In [ ]:
import torch
a=torch.tensor([[[6,18,24],[1,2,3],[2,5,9]]])
a.shape


torch.Size([1, 3, 3])

In [ ]:
import torch
a=torch.tensor([[[6,18,24],[1,2,3]],[[2,5,9],[1,2,3]],[[2,5,9],[3,5,6]]])
a.shape

torch.Size([3, 2, 3])

In [ ]:
import torch
a=torch.tensor([[[6,15,21,8],[4,3,1,2],[4,8,12,16]],[[1,2,3,4],[2,4,6,8],[1,9,16,25]],[[7,14,28,6],[16,24,29,8],[24,18,19,2]]])
a.ndim

3

In [ ]:
import torch
a=torch.tensor([[6,18,24],[1,2,3]])
a[1,1]
a[1:3,2:3]
a[1:2,1:2]

tensor([[2]])

In [ ]:
a[1][1] # indexing

tensor(2)

In [ ]:
# concatination
import torch
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[18,7],[8,9],[10,11]])
print(torch.cat((a,b),dim=0))
print(torch.cat((a,b),dim=1))

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [18,  7],
        [ 8,  9],
        [10, 11]])
tensor([[ 1,  2, 18,  7],
        [ 3,  4,  8,  9],
        [ 5,  6, 10, 11]])


In [ ]:
import torch
a=torch.tensor([[5,6],[3,4],[1,2]])
b=torch.tensor([[19,20],[2,5],[19,32]])
print(torch.cat((a,b),dim=0))
print(torch.cat((a,b),dim=1))

tensor([[ 5,  6],
        [ 3,  4],
        [ 1,  2],
        [19, 20],
        [ 2,  5],
        [19, 32]])
tensor([[ 5,  6, 19, 20],
        [ 3,  4,  2,  5],
        [ 1,  2, 19, 32]])


In [ ]:
import torch
a=torch.tensor([[1,9,10],[1,8,6],[0,1,2]])
b=torch.tensor([[18,7],[8,9],[10,11]])
#print(torch.cat((a,b),dim=0)) # error
print(torch.cat((a,b),dim=1))

tensor([[ 1,  9, 10, 18,  7],
        [ 1,  8,  6,  8,  9],
        [ 0,  1,  2, 10, 11]])


In [ ]:
import torch
a=torch.tensor([[1,2,10],[3,6,4],[5,6,6]])
b=torch.tensor([[18,7],[8,9],[10,11]])
#print(torch.cat((a,b),dim=0))
print(torch.cat((a,b),dim=1))

tensor([[ 1,  2, 10, 18,  7],
        [ 3,  6,  4,  8,  9],
        [ 5,  6,  6, 10, 11]])


In [ ]:
import torch
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[18,7],[8,9],[10,11]])
print(torch.cat((a,b),dim=0))
print(torch.cat((a,b),dim=1))

tensor([[ 1,  2, 18,  7,  8],
        [ 3,  4,  8,  7,  9],
        [ 5,  6,  3, 10, 11]])


In [ ]:
import torch
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[18,7],[8,9]])
print(torch.cat((a,b),dim=0))
#print(torch.cat((a,b),dim=1))

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [18,  7],
        [ 8,  9]])


In [ ]:
# spliting
import torch
a=torch.tensor([1,10,11,12,15,16])
print(torch.split(a,5))
print(torch.split(a,4))
b=torch.arange(20)
print(torch.split(b,[3,7,5,4,1]))
print(torch.chunk(b,3))
c=torch.zeros(4,5,6)
print(c.size(1))
c=torch.ones(4,5,6)
print(c.size(1))

(tensor([ 1, 10, 11, 12, 15]), tensor([16]))
(tensor([ 1, 10, 11, 12]), tensor([15, 16]))
(tensor([0, 1, 2]), tensor([3, 4, 5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14]), tensor([15, 16, 17, 18]), tensor([19]))
(tensor([0, 1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11, 12, 13]), tensor([14, 15, 16, 17, 18, 19]))
5
5


In [ ]:
# operations
import torch
a=torch.tensor([[5,6,7],[8,9,10]])
print(a.sum())
print(a.sum(dim=1))
print(a.sum(dim=0))
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.mean(dim=0,dtype=float))
print(a.mean(dim=1,dtype=float))
print(a.max())
print(a.max(dim=1))
print(a.max(dim=0))

tensor(45)
tensor([18, 27])
tensor([13, 15, 17])
tensor([13, 15, 17])
tensor([18, 27])
tensor([6.5000, 7.5000, 8.5000], dtype=torch.float64)
tensor([6., 9.], dtype=torch.float64)
tensor(10)
torch.return_types.max(
values=tensor([ 7, 10]),
indices=tensor([2, 2]))
torch.return_types.max(
values=tensor([ 8,  9, 10]),
indices=tensor([1, 1, 1]))


In [ ]:
b=torch.tensor([24,36,48,100,56,57])
print(b.size())
print(b.argmax())
print(b.argmin())

torch.Size([6])
tensor(3)
tensor(0)


In [ ]:
a=torch.tensor([[10,4,3],[8,3,2]])
b=torch.tensor([[3,5],[4,8],[1,3]])
print(torch.matmul(a,b))
print(a@b)


tensor([[49, 91],
        [38, 70]])
tensor([[49, 91],
        [38, 70]])


In [ ]:
s=torch.tensor(["balasri"])


ValueError: too many dimensions 'str'

In [ ]:
# library-prebuild code
# frame-work  - it is the path to develop a application ,system ,or software

In [ ]:
# tensor flow
# ml,dl framework ,
# developed by google
# tensor - elements stored in multiple dimentions
# flow- performing operstion on tensor



In [ ]:
import torch
a=torch.tensor([1,2,3])
print(a.device)
torch.cuda.is_available()

cpu


False

In [ ]:
import torch
torch.cuda.is_available()

False