In [ ]:
#tensor flow
# ml,dl framework ,
# developed by google
# tensor - elements stored in multiple dimentions
# flow- performing operstion on tensor
# it is used to building neural network
# CUDA-compute unified device architeture # NUIDIA
# it is used to train model and we can also save thet flow , used to model train , used to prediction generate , model save , operations input


# pytorch developed by meta
# mark zukerberg , he is meta devloper



In [ ]:
import tensorflow as tf
tf.__version__

'2.20.0'

In [ ]:
import tensorflow as tf
a=tf.constant(8)
print(a)

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
b=tf.Variable(9)
print(b)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>


In [ ]:
a=tf.constant([[3,6,9],[7,10,11]])
print(a)

tf.Tensor(
[[ 3  6  9]
 [ 7 10 11]], shape=(2, 3), dtype=int32)


In [ ]:
a=tf.Variable([[3,6,9],[7,10,11]])
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 3,  6,  9],
       [ 7, 10, 11]], dtype=int32)>


In [ ]:
# modify the data use assign
a=tf.Variable([[3,6,9],[7,10,11]])
print(a)
b=a.assign([[1,2,3],[11,12,13]])
print(b)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 3,  6,  9],
       [ 7, 10, 11]], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [11, 12, 13]], dtype=int32)>


In [ ]:
a=tf.constant([[3,6,9],[7,10,11]])
print(a)
b=a.assign([[1,2,3],[11,12,13]])
print(b)

tf.Tensor(
[[ 3  6  9]
 [ 7 10 11]], shape=(2, 3), dtype=int32)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
# 1D
a=tf.constant([1])
print(a)
#2D
b=tf.constant([[1,2,3],[6,4,5]])
print(b)

tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [6 4 5]], shape=(2, 3), dtype=int32)


In [ ]:
tf.range(3,16,3)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15], dtype=int32)>

In [ ]:
tf.fill((3,3),8)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int32)>

In [ ]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros(2)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros((2,3,3))

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
# attributes
a=tf.constant([[1,8,6],[1,10,1]])
print(a)
# shape
print(a.shape)
#dimensions
print(a.ndim)
# type of data
print(a.dtype)
# number of elements
print(tf.size(a))

tf.Tensor(
[[ 1  8  6]
 [ 1 10  1]], shape=(2, 3), dtype=int32)
(2, 3)
2
<dtype: 'int32'>
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
# index based accesing
a=tf.constant([[12,14,18],[4,18,19],[4,38,24]])
print(a[1,1])
print(a[1])
print(a[2])
b=tf.transpose(a)
print(b)
print(b[0])

tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor([ 4 18 19], shape=(3,), dtype=int32)
tf.Tensor([ 4 38 24], shape=(3,), dtype=int32)
tf.Tensor(
[[12  4  4]
 [14 18 38]
 [18 19 24]], shape=(3, 3), dtype=int32)
tf.Tensor([12  4  4], shape=(3,), dtype=int32)


In [ ]:
# slicing based accesing
a=([0,1,5,6],[1,5,4,3],[1,2,3,4,6])

tf.Tensor(
[[0 1 5 6]
 [1 5 4 3]
 [1 2 4 6]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[0 1 1]
 [1 5 2]
 [5 4 4]
 [6 3 6]], shape=(4, 3), dtype=int32)
tf.Tensor([[1 2 4 6]], shape=(1, 4), dtype=int32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [ ]:
import tensorflow as tf
# arthematic operators
a=tf.constant([[3,4],[5,6],[7,8]])
b=tf.constant([[7,8],[8,9]])
print(tf.matmul(a,b))
#print(tf.add(a,b))
#print(tf.subtract(a,b))
#print(tf.divide(a,b))


tf.Tensor(
[[ 53  60]
 [ 83  94]
 [113 128]], shape=(3, 2), dtype=int32)


In [ ]:
a=tf.constant([[3,4],[5,6],[7,8]])
print(tf.reduce_mean(a))
print(tf.reduce_sum(a))
print(tf.reduce_max(a))
print(tf.reduce_prod(a))
print(tf.reduce_min(a))
print(tf.reduce_sum(a,axis=0))
print(tf.reduce_sum(a,axis=1))
#print(tf.reduce_sum(a,dim=1)) # error
print(tf.reduce_max(a,axis=0))
print(tf.reduce_max(a,axis=1))
print(tf.reduce_min(a,axis=0))
print(tf.reduce_min(a,axis=1))
print(tf.reduce_mean(a,axis=0))
print(tf.reduce_mean(a,axis=1))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(33, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(20160, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([15 18], shape=(2,), dtype=int32)
tf.Tensor([ 7 11 15], shape=(3,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)
tf.Tensor([4 6 8], shape=(3,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([3 5 7], shape=(3,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([3 5 7], shape=(3,), dtype=int32)
